version: '3.8'

services:
  db:
    image: postgres:15
    container_name: c2sdb_container
    restart: always
    environment:
      POSTGRES_DB: c2sdb
      POSTGRES_USER: automobile_user
      POSTGRES_PASSWORD: TaEaDWkczafQT@SG
    ports:
      - '5432:5432'
    volumes:
      - ./init/postgres/script.sql:/docker-entrypoint-initdb.d/init-db.sql
